package exception;
import java.util.*;
class MyException extends Exception 
{
	public MyException(String message) 
	{
		super(message);
	}
}

class ExceptionEg
{
 public static void operation(int value) throws MyException 
 {
     if (value < 0) 
     {
         throw new MyException("Value cannot be negative");
     }
     System.out.println("Operation successful with value: " + value);
 }

 public static void main(String[] args) throws Error
 {
	 Scanner sc = new Scanner(System.in);
	 
	 try
	 {
		  Integer[] array = new Integer[10000 * 10000];
	 }
	 catch(Error e)
	 {
		 System.out.println(e.getMessage());
	 }
     try
     {
         int inputValue = sc.nextInt();
         operation(inputValue);
     } 
     catch (MyException e) 
     {
         System.out.println("Custom exception caught: " + e.getMessage());
     }
 }
}

